# Generated by Django 4.1.7 on 2023-03-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("f_publicado", models.DateTimeField(auto_now_add=True)),
                ("tecnologias", models.CharField(max_length=200)),
                ("imagenes", models.ImageField(upload_to="portfolio/imagenes/")),
                ("urls", models.URLField(blank=True)),
            ],
        ),
    ]
