# Generated by Django 4.1.7 on 2023-03-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_rename_project_proyecto"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="titulo",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
