# Generated by Django 4.1.7 on 2023-03-07 01:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_proyecto_titulo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proyecto",
            old_name="urls",
            new_name="url",
        ),
    ]
